### ISSUE TITLE
[Bug]: Link for Goerli testnet Link contract address refers to Sepolia and then has a further link for other testnets

### ISSUE THREAD

**Issue by igneousrock84** [smartcontractkit/documentation#1708]
### Describe the bug

I see a link that is redundant / presumptive / out of order. If I am looking for a contract address, take me to the list of contract / token addresses. Don't take me to instructions, provide a link to instructions from the addresses page please. If i am looking for the contract address there is good chance I may know what I want to do with it.

### To Reproduce

1. Go to 'https://faucets.chain.link/goerli'
2. Click on 'Send me 25 ... Link'
3. See link to obtain contract / token address then goes to this page.

### URLs

- https://docs.chain.link/..
- ...

### Expected behavior

See above in description. I would expect to be given the token address not a set of instructions to then figure out where the link to the contract / token addresses is, in the text.

**Comment by khadni** [comment]
Hi @igneousrock84,

Thank you for bringing up this issue. It would be more convenient if the LINK token address for the chain from which you requested funds from the faucet could be directly copied instead of having to search for it in the documentation.

I will let the team know about this suggestion.
