### ISSUE TITLE
[Enhancement]: 4 digit subscription id 

### ISSUE THREAD

**Issue by neocortexplus** [smartcontractkit/documentation#1942]
### What would you like us to improve?

I really want to know if there is any way to get the 4-digit subscription ID like before, or do new users have to migrate to the new version?

### How important it is?

Many users may have some code, but now they should update the code and migrate to v2.5 if they want to get a new subscription ID.

**Comment by thedriftofwords** [comment]
We recommend migrating to the new version (https://docs.chain.link/vrf/v2-5/migration-from-v2). 

At this time, it's still possible to create a new v2.0 subscription programmatically (by deploying a [subscription manager contract](https://docs.chain.link/vrf/v2/subscription/examples/programmatic-subscription#subscription-manager-contract) that can create and manage new V2.0 subscriptions), but you can no longer create new v2.0 subscriptions in the UI. 

Since your previous workflow is changing either way, the time is better spent on migrating to v2.5 instead of figuring out how to create new v2.0 subscriptions programmatically.

**Comment by thedriftofwords** [comment]
@bsilagani has also provided the following instructions to users on Discord who still want to create VRF V2.0 subscriptions:

1. Access the VRF 2.0 Coordinator Contract: Go to the block explorer (https://sepolia.etherscan.io/address/0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625) and locate the "contract" tab. Under this, you will find "Write Contract."
1. Connect Your Wallet: Click on "Connect to Web" and connect your wallet to the block explorer.
1. Call the createSubscription Function: Locate the "createSubscription" function within the VRF 2.0 Coordinator contract and call it from your connected wallet.
1. Transaction Confirmation: Wait for the transaction to settle. Once confirmed, you will receive a confirmation.
1. Find Subscription ID: Go to https://vrf.chain.link/Sepolia to find your 2.0 subscription ID. This is where you can fund your subscription and add your consumer contracts.

The VRF 2.0 Coordinator contract addresses for all supported networks are on the Supported Networks page:  https://docs.chain.link/vrf/v2/subscription/supported-networks
