### ISSUE TITLE
Add whitelisting Keeper registry

### ISSUE THREAD

**Issue by PatrickAlphaC** [smartcontractkit/documentation#334]
https://keepers.chain.link/?network=mainnet

Right now, we want perforumUpkeep jobs to be able to only be called by the keeper registry. We should have a "best practice" example of how to do this. 

We should also have the registry addresses in our docs for people to get them easier.

**Comment by dwightjl** [comment]
How often do the registry addresses change? If the change is rare, then documenting them is fine.

For restricting function access, will this `onlyBy` modifier example in the Solidty docs work?https://docs.soliditylang.org/en/v0.8.6/common-patterns.html#restricting-access Shall I apply it to the example contract here? https://github.com/smartcontractkit/documentation/blob/main/_includes/samples/Keepers/KeepersCounter.sol

**Comment by aelmanaa** [comment]
@dwightjl  duplicate https://github.com/smartcontractkit/documentation/issues/266 ?

**Comment by aelmanaa** [comment]
thanks, @wentzeld : if re-validation is correctly implemented in performUpkeep then anyone could call performUpkeep. correct?   
Whitelisting the keeper registry is overkill since it would require the admin to implement an access control mechanism (with admin backdoor), an update registry address mechanism, and also regularly monitor Chainlink keepers registry address (since it could be changed)

@PatrickAlphaC closing this issue then. Please re-open it if this should be discussed further. 

thanks a lot
