### ISSUE TITLE
Check to see if Ganache works with Chainlink nodes

### ISSUE THREAD

**Issue by dwightjl** [smartcontractkit/documentation#366]
The FAQ says Ganache won't work with Chainlink nodes. Test and verify that.

https://github.com/smartcontractkit/documentation/blob/main/docs/Additional%20Information/faq.md

**Comment by dmitrydao** [comment]
It kind of works. I recall Bing from the DevRel team was testing it out. I have a doc somewhere.

**Comment by aelmanaa** [comment]
the right link is this one
https://github.com/smartcontractkit/documentation/blob/main/docs/Node%20Operators/running-a-chainlink-node.md

@dwightjl you can run chainlink with ganache. There is an example in [here](https://igudar.medium.com/chainlink-local-development-truffle-ganache-kubernetes-185a8cc2fda0). but you'll need to deploy `Chainlink contracts` or fork an existing testnet.  Hence , what is the purpose of this issue:

- remove `Ganache is a mock testnet and it doesn't work with Chainlink because of that`. Because it is not 100% accurate
- Or write a tutorial showing  how to run a `Chainlink node` locally ?
