### ISSUE TITLE
Add page for Polygon / Matic ENS

### ISSUE THREAD

**Issue by mccordnate** [smartcontractkit/documentation#56]
ENS has been deployed to Polygon by our team.

Let's start with an `ens-polygon.md` page that's linked to on the [ENS docs page](https://docs.chain.link/docs/ens/). 

Example web3 usage of the ENS on Polygon is here:

```const web3 = new Web3("https://rpc-mainnet.matic.network");
web3.eth.ens.registryAddress = "0x37C2058a99A8804bcEE54de1DbCEfC3FA866fF85"
web3.eth.ens.getAddress('eth-usd.data.eth')
  .then((address) => {
    console.log(address)
  })

**Comment by dmitrydao** [comment]
Was this deployed for Price Feeds only or VRF and API Requests too?

**Comment by mccordnate** [comment]
@dmitrydao Anything that can be registered as a name/domain in ENS, but from our side it would just be feeds for now.

**Comment by aelmanaa** [comment]
Hi @mccordnate

first of all, thanks for the effort and sorry for the delay. The recommendation from the ENS team is to **only** use the mainnet "“Our recommendation is simple: always refer to the ENS name on Ethereum mainnet (networkId 1)." ([source](https://medium.com/the-ethereum-name-service/how-to-support-ens-for-multi-chain-dapps-b0a7ff043d77))

Now, because the contracts can have different addresses depending where they are deployed, the ENS team suggests to properly use the _coin type_ field ([source](https://medium.com/the-ethereum-name-service/improved-ens-support-for-evm-compatible-chains-19fc86e9722b))

IMHO, it's an enhancement that we have to carry here: https://app.ens.domains/name/data.eth/details 

Going to open a feature request for the product team 

thanks again for reporting this
