### ISSUE TITLE
Broken link at:  https://mycontract.co/getpricedatafeed

### ISSUE THREAD

**Issue by gpadvorac** [smartcontractkit/documentation#568]
Go to this page:
https://mycontract.co/getpricedatafeed

and you will see the link "CoinMarketCap Chainlink (Testnet)" which is broken.

This is the URL:
https://docs.chain.link/docs/coinmarketcap#section-create-your-chainlinked-contract

**Comment by dwightjl** [comment]
I'm not sure what the history of the target page is. @PatrickAlphaC do you know what this was previously used for? I'm not sure we have a relevant redirect we can add.

**Comment by gpadvorac** [comment]
I’m not sure what you are asking as I have no idea what it was previously used for.

This page
MyContract - Secure, Scalable Blockchain-Agnostic Decentralized Oracle<https://mycontract.co/getpricedatafeed>

Has a broken link here:
***@***.***


Best Regards,

George Padvorac
Partner, NWIS.net L.P.
Office:  281-763-2404
Cell:     832-335-0390
***@***.******@***.***>

**Comment by aelmanaa** [comment]
Hello @gpadvorac 

first of all, thanks for reporting the issue. Since https://mycontract.co is not managed by _chainlink labs_, I've opened an issue on their repo:  https://github.com/XinFinOrg/MyContract/issues/58 
the official documentation can be found here https://docs.chain.link/docs/get-the-latest-price/

please feel free to get back in case something is missing in the official documentation

thanks again
