### ISSUE TITLE
Как  запустит сервер

### ISSUE THREAD

**Issue by pinokio240** [smartcontractkit/documentation#581]
Здравствуйте, просматриваю вашу инструкцию по  установки  базы данных.  Пока у меня не удалось запустить.
Пожалуйста сделайте полное описания для всех настроек и всех программ в одном месте, что бы не бегать и не искать как настроить разные программы и заставить их правильно работать.
 Сделайте такое объяснение чтоб не знающий человек мог разобраться. 
И на последок IP адрес должен быть постоянный?  
 Операционная Система Windows 8 x64

**Comment by aelmanaa** [comment]
@dwightjl is is taken care of by this pull request https://github.com/smartcontractkit/documentation/pull/192 ?

**Comment by dwightjl** [comment]
> @dwightjl is it taken care of by this pull request #192 ?

I made that PR before I joined and haven't looked at it in a while. It certainly resolves some friction that I ran into when I started learning how to run nodes.

Some of the issue here is running on Windows 8, which doesn't support the [WSL](https://docs.microsoft.com/en-us/windows/wsl/install). You might still be able to make this work using Docker natively on Windows 8, but I don't think we officially support that system configuration.

**Comment by aelmanaa** [comment]
@pinokio240 were you able to run your node using docker on windows 8? Closing this issue but please get back should you have further questions
