### ISSUE TITLE
[Bug]: Any API demo- following the instructions in the Chainlink docs results in an transaction error when calling  requestVolumeData()

### ISSUE THREAD

**Issue by uwieske** [smartcontractkit/documentation#731]
### Describe the bug

Hi,

I am reading and following the docs on how to deploy and use the Any API, but I am keep getting a transaction failure on chain (Kovan).

 

### To Reproduce

1) Open Remix (in https://docs.chain.link/docs/make-a-http-get-request/)
2) Compile in Remix APIConsumer contract
3) switch to my appropriate Meta Mask account containing ETHs and LINK connected to Kovan Testnet
4) Make sure APIConsumer contract is selected for deployment in Remix and making the deployment by clicking on Deploy button, confirm in MetaMask for the deployment fee/cost [Transaction Succeeds after a while and verified as such on etherscan)
5) In Remix I click on the requestVolumeData-button
6) I get a warning about "Gas estimation failed" ....bla bla... my options at this point "cancel tx" or (still forcibly) "send tx". I choose for "send tx". 
7)  MetaMask is displayed: options "reject" or "confirm" [ I verified again that I had sufficient funding. A total cost of 0.075 ETH would be charged. At this point I knew that my wallet contained more than 0.2 ETH  and I confirmed.

RESULT: Transaction failed. 
Also checked on etherscan. I saw a "bad instruction" message in the transaction log (as tooltip information).

**Note**: GasLimit in Remix is set at: 30000000
 

### URLs

1. https://docs.chain.link/docs/make-a-http-get-request/
2. https://remix.ethereum.org/#url=https://docs.chain.link/samples/APIRequests/APIConsumer.sol&optimize=false&runs=200&evmVersion=null&version=soljson-v0.8.7+commit.e28d00a7.js 

### Expected behavior

Transaction should not fail according to the documentation instructions.
And I should be able to continue by submitting on the button requestVolumeData in Remix.

### Additional context

I have checked with market.link (jobs)
I do not see a job for Kovan net related to Get > CryptoCompare ETH -> USD, that is, for the transformation of a type like the  API endpoint: https://min-api.cryptocompare.com/data/pricemultifull?fsyms=ETH&tsyms=USD  
 
Note: I've also noticed that in general most jobs in Chainlink Market are marked as "whitelisted" and that the operator should be contacted. (?) --> is this issue related to access management may be??

**Comment by aelmanaa** [comment]
Hello @uwieske 

thank you for opening the issue.

- Have you funded your contract with 0,1 LINK before calling `requestVolumeData` ?  If not , please follow these [instructions](https://docs.chain.link/docs/fund-your-contract/)
- The job used is not specialized to only returning cryptocurrencies prices.  You have to look for `GET > Uint256`jobs because you are looking for a job which performs a HTTP GET Request and returns an insigned integer to your smart contract. 

ps: Note that we are currently reviewing the ANY API Examples as some of the current ones do not work anymore. If you are looking to test the other "Connect to ANY API" examples then have a look at this [docs preview](https://documentation-git-aelmanaa-any-api-fetch-f-118d9c-chainlinklabs.vercel.app/docs/make-a-http-get-request/), even though it is still a WIP

Closing this issue but please don't hesitate to get back should you have any questions/remarks

**Comment by uwieske** [comment]
Hi aelmanaa
Indeed, I have just realized that I am not funding my contract after deployment and wanted to revert this issue and wanted to close this misplaced issue. Thanks for replying. Is it a good idea to place a reminder/notice in the documentation immediately after or before the point where the reader is indicated to "Open Remix", may be? Stupid of me not to realize that I was not funding my contract. (did not realize the indirection of my call to the contract which would create the downstream call.)
Thanks for indicating about the ongoing changes in the examples (and docs). I will take your suggestion into account. 
 
Issue resolved. Issue may be closed. thanks!
