### ISSUE TITLE
[Bug]: broken link

### ISSUE THREAD

**Issue by dewedeth** [smartcontractkit/documentation#757]
### Describe the bug

showing error captain 404
when pressing the  "choosing a random seed" link.  not sure if bug or maybe I have no access,
![image](https://user-images.githubusercontent.com/105073106/168501009-21efebaa-b180-4e0e-ab0c-ee31043fb747.png)

### To Reproduce

3. See error
![image](https://user-images.githubusercontent.com/105073106/168500923-d2521a11-1649-4bdc-92ab-3b05400761db.png)

### URLs

- https://docs.chain.link/..
- ...
 https://docs.chain.link/docs/chainlink-vrf-api-reference#choosing-a-seed

### Expected behavior

it should have reloaded

**Comment by aelmanaa** [comment]
Hello @dewedeth 

thank you very much for contacting us. For future reference, this issue is related to https://blog.chain.link  (https://blog.chain.link/random-numbers-nft-erc721/ to be exact). 
The tutorial was written in 2020 and was using a legacy implementation of VRF. These tutorials will need to be updated.

Meanwhile, I strongly advise you to focus on VRF v2:

- [intro to VRF](https://docs.chain.link/docs/chainlink-vrf/)
- [Get a random number](https://docs.chain.link/docs/get-a-random-number/)
- [Roll dice example](https://docs.chain.link/docs/intermediates-tutorial/)
